### ISSUE TITLE
Test failure with libgit2-dev 1.3.0

### ISSUE THREAD

**Issue by gregoa** [jacquesg/p5-Git-Raw#222]
We have the following bug report in Debian: https://bugs.debian.org/1009031

Please note that we are building against the _system_ libgit2.

```
#   Failed test at t/02-commit.t line 318.
#          got: '
# From 1f1a8656048c7249835439f7072aeff78b8edd7f Mon Sep 17 00:00:00 2001
# From: Git::Raw author <git-xs@example.com>
# Subject: [1/2] second commit
#
# ---
#  test2 | 1 +
#  1 file changed, 1 insertion(+)
#  create mode 100644 test2
#
# diff --git a/test2 b/test2
# new file mode 100644
# index 0000000..7b79d2f
# --- /dev/null
# +++ b/test2
# @@ -0,0 +1 @@
# +this is a second test
# \ No newline at end of file
# --
# libgit2
# '
#     expected: '
# From 1f1a8656048c7249835439f7072aeff78b8edd7f Mon Sep 17 00:00:00 2001
# From: Git::Raw author <git-xs@example.com>
# Subject: second commit
#
# ---
#  test2 | 1 +
#  1 file changed, 1 insertion(+)
#  create mode 100644 test2
#
# diff --git a/test2 b/test2
# new file mode 100644
# index 0000000..7b79d2f
# --- /dev/null
# +++ b/test2
# @@ -0,0 +1 @@
# +this is a second test
# \ No newline at end of file
# --
# libgit2
# '
# Looks like you failed 1 test of 173.
t/02-commit.t ...
```

The test at line 318 is the one where `exclude_subject_patch_marker` is set; apparently this does'nt work anymore with libgit2 1.3.0; the actual diff off the test failure above is:
```
@@ -1,6 +1,6 @@
 # From 10bcecbc1cc736d968ce8d79846be5075a30f7b2 Mon Sep 17 00:00:00 2001
 # From: Git::Raw author <git-xs@example.com>
-# Subject: second commit
+# Subject: [1/2] second commit
 # 
 # ---
 #  test2 | 1 +
```

This might be related to https://github.com/libgit2/libgit2/pull/6061 …

**Comment by jacquesg** [comment]
This is due to the Debian maintainers replacing the bundled copy of libgit2 with a copy that was built externally. You're lucky that this is the only fallout.

Playing outside of the parameters and scope of the module does not constitute a bug with this project.

If you feel that the copy of libgit2 bundled in the distribution is outdated or is lacking something, feel free to open a pull request to update to a more recent version.

**Comment by gregoa** [comment]
On Sat, 23 Apr 2022 02:30:57 -0700, Jacques Germishuys wrote:

> This is due to the Debian maintainers replacing the bundled copy of
> libgit2 with a copy that was built externally.

Correct, that's why I explicitly mentioned it.

> Playing outside of the parameters and scope of the module does not
> constitute a bug with this project.

True. I should have mentioned that this is less of a bug report and
more of a headsup for the case when you update the bundled libgit2.
 

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by jacquesg** [comment]
Thank you. It is something I'm aware of, they get picked up by the test/release process currently, and does require me to change 2 or 3 lines of code during each minor bump.

**Comment by real-dam** [comment]
Any news?
If you can point to the couple of lines that needs changing we can apply the change as a patch to the Debian package until it is release officially.
Thanks!

**Comment by jacquesg** [comment]
@real-dam The patch is already available. If I apply it to the main branch, it will result in test case failures. An upgrade of the bundled libgit2 library is required, which isn't as simple as changing 2 or 3 lines of code due to compatibility issues I would need to take care of, document, fix or whatever.

**Comment by mdb571** [comment]
Hey there, 
Just a little headsup, libgit2 has 1.4.3 as its latest version and the same has been already uploaded to Debian [experimental](https://tracker.debian.org/pkg/libgit2). So I think it would be better to bump (if you're planning to do so) the bundled libgit2 version to the latest so as to avoid extra work or you can point us to the relevant patch that  supports the upgrade and it can be applied to the Debian package so that things we'll be smooth in Debian and you can work on the official release at your ease.

**Comment by xtaran** [comment]
@mdb571:
> ibgit2 has 1.4.3 as its latest version and the same has been already uploaded to Debian [experimental](https://tracker.debian.org/pkg/libgit2). So I think it would be better to bump (if you're planning to do so) the bundled libgit2 version to the latest so as to avoid extra work

[Using bundled libraries is a strong no-go in Debian](https://wiki.debian.org/EmbeddedCopies), at least if the bundled library is packaged already in Debian.

And actually bundling it adds additional security-maintenance (and responsibility) to the developers as well as to anyone using it.

**Comment by jacquesg** [comment]
Just because its the Debian way doesn't mean the approach works for other people. As per my previous comment, if you feel that something should change, please submit a PR, bearing in mind, that this gets used on numerous other systems.

Also bear in mind that this package predates any stable releases from libgit2, hence the pinning to a specific commit.

**Comment by jacquesg** [comment]
Version 0.89 has been compiled against 1.5.0 of libgit2.
